<template>
  <UDashboardPanel id="coaching-athletes">
    <template #header>
      <UDashboardNavbar>
        <template #leading>
          <UDashboardSidebarCollapse />
        </template>
        <template #title>
          <CoachingNavbarLinks />
        </template>
        <template #right>
          <div class="flex items-center gap-2">
            <ClientOnly>
              <DashboardTriggerMonitorButton />
            </ClientOnly>
            <UButton
              color="primary"
              variant="solid"
              icon="i-heroicons-user-plus"
              size="sm"
              class="font-bold"
              @click="isConnectModalOpen = true"
            >
              Add Athlete
            </UButton>
          </div>
        </template>
      </UDashboardNavbar>
    </template>

    <template #body>
      <div class="p-0 sm:p-6 space-y-6">
        <div class="px-4 sm:px-0">
          <h1 class="text-4xl font-black text-gray-900 dark:text-white uppercase tracking-tight">
            My Athletes
          </h1>
          <p
            class="text-[10px] font-bold text-gray-500 dark:text-gray-400 uppercase tracking-[0.2em] mt-1 italic"
          >
            Managing Your Performance Roster
          </p>
        </div>

        <CoachingGroupManager
          v-if="athletes.length > 0 || groups.length > 0"
          v-model:active-group-id="activeGroupId"
          :groups="groups"
          :athletes="athletes"
          :teams="teams"
          @refresh="fetchGroups"
        />

        <div v-if="loading" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <UCard v-for="i in 3" :key="i">
            <template #header>
              <div class="flex items-center gap-3">
                <USkeleton class="h-12 w-12 rounded-full" />
                <div class="space-y-2">
                  <USkeleton class="h-4 w-32" />
                  <USkeleton class="h-3 w-48" />
                </div>
              </div>
            </template>
            <USkeleton class="h-20 w-full rounded-lg" />
          </UCard>
        </div>

        <div
          v-else-if="athletes.length === 0"
          class="py-12 text-center flex flex-col items-center justify-center border-2 border-dashed border-gray-200 dark:border-gray-800 rounded-lg"
        >
          <div class="bg-neutral-100 dark:bg-neutral-800 p-4 rounded-full mb-4">
            <UIcon name="i-heroicons-users" class="w-8 h-8 text-neutral-400" />
          </div>
          <h3 class="font-bold text-lg">No Athletes Yet</h3>
          <p class="text-neutral-500 mb-6 max-w-xs">
            Ask your athlete for their invite code to start coaching them.
          </p>
          <UButton
            color="primary"
            label="Connect Athlete"
            icon="i-heroicons-user-plus"
            @click="isConnectModalOpen = true"
          />
        </div>

        <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <CoachingAthleteCard
            v-for="rel in filteredAthletes"
            :key="rel.id"
            :athlete="rel.athlete"
            @view="viewAthlete"
            @message="messageAthlete"
          />
        </div>

        <div
          v-if="activeGroupId !== 'all' && filteredAthletes.length === 0"
          class="py-12 text-center flex flex-col items-center justify-center bg-neutral-50 dark:bg-neutral-800/20 rounded-lg border border-gray-100 dark:border-gray-800"
        >
          <p class="text-neutral-500 text-sm italic font-medium">
            No athletes assigned to this group yet.
          </p>
        </div>
      </div>
    </template>
  </UDashboardPanel>

  <!-- Connect Athlete Modal -->
  <UModal
    v-model:open="isConnectModalOpen"
    title="Add New Athlete"
    description="Establish a direct coaching relationship by entering the unique invite code provided by your athlete."
  >
    <template #body>
      <UFormField
        label="Athlete Invite Code"
        help="Codes are 6 characters long (e.g. AB12XY) and are generated by the athlete in their 'My Team' section."
      >
        <UInput
          v-model="connectCode"
          placeholder="ENTER-CODE"
          class="font-mono uppercase text-center text-xl w-full"
          maxlength="6"
        />
      </UFormField>
    </template>
    <template #footer>
      <UButton label="Cancel" color="neutral" variant="ghost" @click="isConnectModalOpen = false" />
      <UButton
        label="Connect Athlete"
        color="primary"
        :loading="connecting"
        :disabled="!connectCode || connectCode.length < 6"
        @click="connectAthlete"
      />
    </template>
  </UModal>
</template>

<script setup lang="ts">
  definePageMeta({
    middleware: 'auth'
  })

  useHead({
    title: 'My Athletes | Coaching',
    meta: [
      {
        name: 'description',
        content: 'Manage the athletes you are currently coaching.'
      }
    ]
  })

  const athletes = ref<any[]>([])
  const groups = ref<any[]>([])
  const teams = ref<any[]>([])
  const activeGroupId = ref('all')
  const loading = ref(true)
  const connecting = ref(false)
  const isConnectModalOpen = ref(false)
  const connectCode = ref('')
  const toast = useToast()
  const router = useRouter()

  const filteredAthletes = computed(() => {
    if (activeGroupId.value === 'all') return athletes.value
    const group = groups.value.find((g) => g.id === activeGroupId.value)
    if (!group) return athletes.value
    const memberIds = group.members?.map((m: any) => m.athleteId) || []
    return athletes.value.filter((rel) => memberIds.includes(rel.athlete.id))
  })

  async function fetchData() {
    loading.value = true
    try {
      const [athletesData, groupsData, teamsData] = await Promise.all([
        $fetch('/api/coaching/athletes'),
        $fetch('/api/coaching/groups'),
        $fetch('/api/coaching/teams')
      ])
      athletes.value = athletesData as any[]
      groups.value = groupsData as any[]
      teams.value = teamsData as any[]
    } catch (e) {
      console.error(e)
      toast.add({ title: 'Failed to load coaching data', color: 'error' })
    } finally {
      loading.value = false
    }
  }

  async function fetchGroups() {
    try {
      groups.value = (await $fetch('/api/coaching/groups')) as any[]
    } catch (e) {
      console.error(e)
    }
  }

  async function connectAthlete() {
    connecting.value = true
    try {
      await $fetch('/api/coaching/athletes/connect', {
        method: 'POST',
        body: { code: connectCode.value.toUpperCase() }
      })
      toast.add({ title: 'Athlete connected successfully!', color: 'success' })
      await fetchData()
      isConnectModalOpen.value = false
      connectCode.value = ''
    } catch (err: any) {
      toast.add({
        title: 'Failed to connect: ' + (err.data?.message || 'Invalid code'),
        color: 'error'
      })
    } finally {
      connecting.value = false
    }
  }

  function viewAthlete(athlete: any) {
    router.push(`/coaching/athletes/${athlete.id}`)
  }

  function messageAthlete(athlete: any) {
    router.push('/chat')
  }

  onMounted(fetchData)
</script>
