-- AlterTable
ALTER TABLE "UserNutritionSettings" ADD COLUMN     "fuelState1Max" DOUBLE PRECISION NOT NULL DEFAULT 4.5,
ADD COLUMN     "fuelState1Min" DOUBLE PRECISION NOT NULL DEFAULT 3.0,
ADD COLUMN     "fuelState1Trigger" DOUBLE PRECISION NOT NULL DEFAULT 0.60,
ADD COLUMN     "fuelState2Max" DOUBLE PRECISION NOT NULL DEFAULT 7.5,
ADD COLUMN     "fuelState2Min" DOUBLE PRECISION NOT NULL DEFAULT 5.0,
ADD COLUMN     "fuelState2Trigger" DOUBLE PRECISION NOT NULL DEFAULT 0.85,
ADD COLUMN     "fuelState3Max" DOUBLE PRECISION NOT NULL DEFAULT 12.0,
ADD COLUMN     "fuelState3Min" DOUBLE PRECISION NOT NULL DEFAULT 8.0,
ADD COLUMN     "fuelingSensitivity" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
