<template>
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900 flex flex-col">
    <header
      class="sticky top-0 z-50 bg-white/75 dark:bg-gray-950/75 backdrop-blur border-b border-gray-200 dark:border-gray-800"
    >
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
          <NuxtLink to="/" class="flex items-center hover:opacity-90 transition-opacity">
            <img
              src="/media/coach-watts.webp"
              alt="Coach Watts"
              class="h-12 w-auto object-contain"
            />
          </NuxtLink>
          <div class="flex items-center gap-4">
            <div class="hidden sm:flex items-center gap-2">
              <UButton
                v-if="route.path !== '/login'"
                to="/login"
                variant="ghost"
                color="neutral"
                size="sm"
              >
                Sign In
              </UButton>
              <UButton v-if="route.path !== '/join'" to="/join" color="primary" size="sm">
                Get Started
              </UButton>
            </div>
            <ColorModeButton />
            <UPopover class="sm:hidden">
              <UButton icon="i-lucide-menu" color="neutral" variant="ghost" />
              <template #content>
                <div class="p-3 w-44 flex flex-col gap-2">
                  <UButton
                    v-if="route.path !== '/login'"
                    to="/login"
                    variant="ghost"
                    color="neutral"
                    block
                  >
                    Sign In
                  </UButton>
                  <UButton v-if="route.path !== '/join'" to="/join" color="primary" block>
                    Get Started
                  </UButton>
                </div>
              </template>
            </UPopover>
          </div>
        </div>
      </div>
    </header>

    <main class="flex-1">
      <slot />

      <SharePageCTA />
    </main>

    <!-- Footer -->
    <footer
      class="mt-auto py-12 px-6 border-t border-gray-200 dark:border-gray-700 text-center bg-white dark:bg-gray-800"
    >
      <p class="text-sm text-gray-500 dark:text-gray-400">
        Generated by
        <a href="https://coachwatts.com/" class="font-bold text-primary-500 hover:underline"
          >Coach Wattz</a
        >
      </p>
      <p class="text-xs text-gray-400 dark:text-gray-500 mt-2">
        Personalized AI Endurance Coaching
      </p>
    </footer>
  </div>
</template>

<script setup lang="ts">
  const route = useRoute()
</script>
